[2024-07-19T17:30:04.288+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-19T17:30:04.315+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: newdag.e_valida scheduled__2024-07-19T16:30:00+00:00 [queued]>
[2024-07-19T17:30:04.324+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: newdag.e_valida scheduled__2024-07-19T16:30:00+00:00 [queued]>
[2024-07-19T17:30:04.325+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-19T17:30:04.339+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): e_valida> on 2024-07-19 16:30:00+00:00
[2024-07-19T17:30:04.346+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=3733) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-19T17:30:04.347+0000] {standard_task_runner.py:64} INFO - Started process 3735 to run task
[2024-07-19T17:30:04.347+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'newdag', 'e_valida', 'scheduled__2024-07-19T16:30:00+00:00', '--job-id', '77', '--raw', '--subdir', 'DAGS_FOLDER/newdag.py', '--cfg-path', '/tmp/tmpofscgyug']
[2024-07-19T17:30:04.349+0000] {standard_task_runner.py:91} INFO - Job 77: Subtask e_valida
[2024-07-19T17:30:04.391+0000] {task_command.py:426} INFO - Running <TaskInstance: newdag.e_valida scheduled__2024-07-19T16:30:00+00:00 [running]> on host 11dd3049148c
[2024-07-19T17:30:04.480+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='newdag' AIRFLOW_CTX_TASK_ID='e_valida' AIRFLOW_CTX_EXECUTION_DATE='2024-07-19T16:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-19T16:30:00+00:00'
[2024-07-19T17:30:04.482+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-19T17:30:04.483+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2024-07-19T17:30:04.492+0000] {python.py:237} INFO - Done. Returned value was: valido
[2024-07-19T17:30:04.493+0000] {branch.py:36} INFO - Branch into valido
[2024-07-19T17:30:04.494+0000] {skipmixin.py:178} INFO - Following branch valido
[2024-07-19T17:30:04.508+0000] {skipmixin.py:246} INFO - Skipping tasks [('nvalido', -1)]
[2024-07-19T17:30:04.531+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-19T17:30:04.549+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=newdag, task_id=e_valida, run_id=scheduled__2024-07-19T16:30:00+00:00, execution_date=20240719T163000, start_date=20240719T173004, end_date=20240719T173004
[2024-07-19T17:30:04.601+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-07-19T17:30:04.627+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-19T17:30:04.629+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
