[2024-07-24T13:37:49.999+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T13:37:50.019+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dagCursea.unzip_data scheduled__2024-07-24T12:30:00+00:00 [queued]>
[2024-07-24T13:37:50.025+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dagCursea.unzip_data scheduled__2024-07-24T12:30:00+00:00 [queued]>
[2024-07-24T13:37:50.025+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-24T13:37:50.039+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): unzip_data> on 2024-07-24 12:30:00+00:00
[2024-07-24T13:37:50.045+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=67) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T13:37:50.046+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dagCursea', 'unzip_data', 'scheduled__2024-07-24T12:30:00+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/__pycache__/text.py', '--cfg-path', '/tmp/tmp_9toz9nc']
[2024-07-24T13:37:50.047+0000] {standard_task_runner.py:64} INFO - Started process 69 to run task
[2024-07-24T13:37:50.047+0000] {standard_task_runner.py:91} INFO - Job 94: Subtask unzip_data
[2024-07-24T13:37:50.082+0000] {task_command.py:426} INFO - Running <TaskInstance: dagCursea.unzip_data scheduled__2024-07-24T12:30:00+00:00 [running]> on host 0313639cbb41
[2024-07-24T13:37:50.147+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dagCursea' AIRFLOW_CTX_TASK_ID='unzip_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-24T12:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-24T12:30:00+00:00'
[2024-07-24T13:37:50.148+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T13:37:50.149+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-24T13:37:50.149+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'unzip -u /Documents/dado.zip -d /Documents']
[2024-07-24T13:37:50.159+0000] {subprocess.py:86} INFO - Output:
[2024-07-24T13:37:50.161+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: unzip: command not found
[2024-07-24T13:37:50.162+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-07-24T13:37:50.162+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T13:37:50.170+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-07-24T13:37:50.173+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dagCursea, task_id=unzip_data, run_id=scheduled__2024-07-24T12:30:00+00:00, execution_date=20240724T123000, start_date=20240724T133750, end_date=20240724T133750
[2024-07-24T13:37:50.184+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 94 for task unzip_data (Bash command failed. The command returned a non-zero exit code 127.; 69)
[2024-07-24T13:37:50.220+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T13:37:50.241+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T13:37:50.244+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
