[2024-07-24T13:38:49.982+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-24T13:38:50.008+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dagCursea.unzip_data scheduled__2024-07-23T15:30:00+00:00 [queued]>
[2024-07-24T13:38:50.016+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dagCursea.unzip_data scheduled__2024-07-23T15:30:00+00:00 [queued]>
[2024-07-24T13:38:50.017+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-07-24T13:38:50.031+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): unzip_data> on 2024-07-23 15:30:00+00:00
[2024-07-24T13:38:50.040+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=78) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-24T13:38:50.042+0000] {standard_task_runner.py:64} INFO - Started process 88 to run task
[2024-07-24T13:38:50.042+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dagCursea', 'unzip_data', 'scheduled__2024-07-23T15:30:00+00:00', '--job-id', '95', '--raw', '--subdir', 'DAGS_FOLDER/__pycache__/text.py', '--cfg-path', '/tmp/tmptksqa82q']
[2024-07-24T13:38:50.043+0000] {standard_task_runner.py:91} INFO - Job 95: Subtask unzip_data
[2024-07-24T13:38:50.100+0000] {task_command.py:426} INFO - Running <TaskInstance: dagCursea.unzip_data scheduled__2024-07-23T15:30:00+00:00 [running]> on host 0313639cbb41
[2024-07-24T13:38:50.198+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dagCursea' AIRFLOW_CTX_TASK_ID='unzip_data' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T15:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-23T15:30:00+00:00'
[2024-07-24T13:38:50.199+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-24T13:38:50.200+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-24T13:38:50.201+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'unzip -u /Documents/dado.zip -d /Documents']
[2024-07-24T13:38:50.224+0000] {subprocess.py:86} INFO - Output:
[2024-07-24T13:38:50.226+0000] {subprocess.py:93} INFO - /usr/bin/bash: line 1: unzip: command not found
[2024-07-24T13:38:50.227+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2024-07-24T13:38:50.228+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-24T13:38:50.240+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2024-07-24T13:38:50.244+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=dagCursea, task_id=unzip_data, run_id=scheduled__2024-07-23T15:30:00+00:00, execution_date=20240723T153000, start_date=20240724T133850, end_date=20240724T133850
[2024-07-24T13:38:50.257+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 95 for task unzip_data (Bash command failed. The command returned a non-zero exit code 127.; 88)
[2024-07-24T13:38:50.296+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-07-24T13:38:50.322+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-24T13:38:50.328+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
